---
underlay:
  build_dir: "files/builds/{{ inventory_hostname }}"
  conf_dir: "files/configs/{{ inventory_hostname }}"
  conf: "files/configs/{{ inventory_hostname }}/{{ inventory_hostname }}.conf"

  ebgp:
    local_asn: 65001
    import: underlay-ebgp-in
    export: underlay-ebgp-out
    type: external
    mtu_discovery: yes
    multipath: multiple-as

    bfd:
      minimum_interval: 500
      multiplier: 3
      session_mode: automatic
