- name: Generate and Deploy Configuration on Spine
  hosts: juniper:&spine
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: "gather_facts: junos"
      junos_facts:
      register: ansible_junos_facts

    - name: "Build configuration"
      template:
        src: vqfx.conf.j2
        dest: "{{ junos_conf }}"

    - name: "Deploy config to device"
      junos_config:
        backup: yes
        src: "{{ junos_conf }}"
        update: override
