---
# Configure the vlans as per vlan items
- name: config vlans
  eos_config:
    src: "{{ device_os}}.j2"
    defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save config
  with_items: "{{ vlans | default([]) }}"
  when: item.vlanid is defined
  tags:
  - config
  - vlan
  - eos

# Run the command to show vlans
- name: show vlan
  eos_command:
    defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
    commands:
      - command: show vlan
  register: show_vlan
  tags:
  - show
  - vlan
  - eos

# Print the output of "show vlan" task
- debug: var="{{ show_vlan.stdout | to_nice_json }}"
  when: show_vlan is defined
  tags:
  - show
  - vlan
  - eos
