
loopback_ip: 1.1.1.14

underlay:
  local:
    asn: 60014
  neighbors:
    - interface: eth1
      name: spine1
      asn: 60001
      peer_ip: "{{ p2p.link7.1 }}"
      local_ip: "{{ p2p.link7.2 }}"
    - interface: eth2
      name: spine2
      asn: 60002
      peer_ip: "{{ p2p.link8.1 }}"
      local_ip: "{{ p2p.link8.2 }}"
