- name: "Configure logging for messages"
  junos_logging:
    dest: file
    name: messages
    facility: any
    level: notice

- name: "Configure logging for user"
  junos_logging:
    dest: user
    name: '*'
    facility: any
    level: emergency
