- name: "Build Topology"
  block:
    - name: "Git clone Darkbulb"
      become: true
      become_user: "{{ owner }}"
      git:
        repo: 'https://github.com/victorock/darkbulb.git'
        version: dev
        clone: yes
        dest: "darkbulb"
        force: yes
    - name: "Create directories"
      file:
        path: "darkbulb/topologies/files/{{ vagrant_template_dir.path }}"
        state: directory
      with_filetree: "darkbulb/topologies/cisco/templates/{{ provider }}"
      when: vagrant_template_dir.state == 'directory'
      loop_control:
        loop_var: vagrant_template_dir

    - name: "Process Vagrant Templates"
      template:
        src: "{{ vagrant_template_file.src }}"
        dest: "darkbulb/topologies/files/{{ vagrant_template_file.path }}"
      with_filetree: "darkbulb/topologies/cisco/templates/{{ provider }}"
      when: vagrant_template_file.state == 'file'
      loop_control:
        loop_var: vagrant_template_file
