---
# This playbook will generate and apply configuration to all of the devices

- include: pb.conf.all.yaml
- name: Apply configuration
  hosts: vqfx10k
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Pushing config ... please wait
      junos_install_config:
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port }}"
        user: root
        passwd: Juniper
        file: "{{ junos_conf }}"
        overwrite: yes
        replace: no
