---
- name: "Create resource group"
  azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  register: return_azure_rm_resourcegroup

- debug: var=return_azure_rm_resourcegroup
  when: azure_cloud_rm_resourcegroup

- name: Create VM accessible via ssh keys only
  azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: testvm20
      short_hostname: testvm20
      ssh_password_enabled: false
      ssh_public_keys: "{{ ssh_keys }}"
      vm_size: Standard_D1
      admin_username: chouseknecht
      image: "{{ image }}"
  register: output

- debug: var=output
  when: playbook_debug

- name: "Add instance to inventory groups [ darkbulb ]"
  add_host:
    name: "{{ student }}"
    ansible_host: "{{ azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    student: "{{ student }}"
    groupname: "darkbulb"
  with_items: "{{ return_gce_cloud_instance.instance_data }}"
  tags:
    - create

- name: "Wait for SSH for student instance"
  wait_for:
    delay: 1
    host: "{{ item.public_ip }}"
    port: 22
    state: started
    timeout: 60
  with_items: "{{ return_gce_cloud_instance.instance_data }}"
  tags:
    - create
