- name: "Transpose topology information as columns: left_nodes, right_nodes, left_roles, right_roles, left_links, right_links"
  set_fact:
    left_nodes: "{{  topology|json_query('[*].left_node') }}"
    right_nodes: "{{ topology|json_query('[*].right_node') }}"
    left_roles: "{{  topology|json_query('[*].left_role') }}"
    right_roles: "{{ topology|json_query('[*].right_role') }}"
    left_links: "{{  topology|json_query('[*].left_link') }}"
    right_links: "{{ topology|json_query('[*].right_link') }}"

- name: "Check topology roles"
  block:
    - name: "Check for missing roles in the left"
      fail:
        msg: "Left Node missing role"
      when: (left_nodes|length) != (left_roles|length)

    - name: "Check for missing roles in the right"
      fail:
        msg: "Right Node missing role"
      when: (right_nodes|length) != (right_roles|length)

- name: "Check topology links"
  block:
    - name: "Check for missing links in the left"
      fail:
        msg: "Left Node missing link"
      when: (left_links|length) != (left_links|length)

    - name: "Check for missing links in the right"
      fail:
        msg: "Right Node missing link"
      when: (left_links|length) != (right_links|length)

- name: "Consolidate topology as columns: nodes, roles, links, where each column = concatenation of left + right"
  set_fact:
    nodes: "{{ (left_nodes+right_nodes) }}"
    roles: "{{ (left_roles+right_roles) }}"
    links: "{{ (left_links+right_links) }}"
