- name: Generate and Deploy Configuration
  hosts: juniper
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: "gather_facts: junos"
      junos_facts:

    - name: "Build configuration"
      template:
        src: vqfx.conf.j2
        dest: "configs/{{ inventory_hostname }}.conf"

    - name: "Deploy config to device"
      junos_config:
        backup: yes
        src: "configs/{{ inventory_hostname }}.conf"
        update: merge
