---
- name: "Underlay L3 Configuration"
  block:
    - name: "left_members"
      junos_l3_interface:
        name: "{{ left.left_port }}"
        ipv4: "{{ left.left_ip }}"
      when: inventory_hostname in left.left_member
      loop_control:
        loop_var: left
        label: "{{ left.left_member }}"
      with_items: "{{ topology }}"

    - name: "right_members"
      junos_l3_interface:
        name: "{{ right.right_port }}"
        ipv4: "{{ right.right_ip }}"
      when: inventory_hostname in right.right_member
      with_items: "{{ topology }}"
      loop_control:
        loop_var: right
        label: "{{ right.right_member }}"
