---
- name: "Create resource group"
  azure_rm_resourcegroup:
      name: "{{ azure_cloud_resource_group }}"
      location: "{{ azure_cloud_location }}"
  register: return_azure_rm_resourcegroup

- debug: var=return_azure_rm_resourcegroup
  when: azure_cloud_rm_resourcegroup

- name: Create VM accessible via ssh keys only
  azure_rm_virtualmachine:
      resource_group: "{{ azure_cloud_resource_group }}"
      name: "{{ student }}"
      admin_username: "instructor"
      ssh_password_enabled: false
      ssh_public_keys: "{{ ssh_keys }}"
      vm_size: "{{ azure_cloud_vm_size }}"
      image: "{{ azure_cloud_image }}"
  register: return_azure_cloud_rm_virtualmachine

- debug: var=return_azure_cloud_rm_virtualmachine
  when: azure_cloud_debug

- name: "Add instance to inventory groups [ darkbulb ]"
  add_host:
    name: "{{ student }}"
    ansible_host: "{{ azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    student: "{{ student }}"
    groupname: "darkbulb"
  tags:
    - create

- name: "Wait for SSH for student instance"
  wait_for:
    delay: 1
    host: "{{ ansible_host }}"
    port: 22
    state: started
    timeout: 60
  tags:
    - create
