---
- name: "Darkbulb Libvirt packages state is latest"
  become: true
  yum:
    name: "{{ libvirt_package }}"
    state: latest
    update_cache: yes
  with_items:
    - epel-release
    - qemu-kvm
    - qemu-img
    - qemu-kvm-tools
    - virt-top
    - virt-install
    - libvirt
    - libvirt-python
    - libvirt-client
  loop_control:
    loop_var: libvirt_package
    label: "{{ libvirt_package }}"
  tags:
    - install

- name: "Push Libvirt files to owner's machine"
  become: true
  become_user: "{{ owner }}"
  copy:
    src: "files/images/qcow2/{{ qcow2_file.path }}"
    dest: "/home/{{ owner }}/images/qcow2/{{ qcow2_file.path }}"
    force: no
  with_filetree: "files/images/qcow2"
  when: qcow2_file.state == 'file'
  loop_control:
    loop_var: qcow2_file
    label: "{{ qcow2_file.path }}"
  tags:
    - install
