---
- name: "Ansible Repo is present"
  become: true
  yum_repository:
    name: ansible_release
    description: "CentOS-$releasever / $basearch - Ansible"
    baseurl: "http://releases.ansible.com/ansible/rpm/release/epel-$releasever-$basearch"
    gpgcheck: no
    enabled: yes
    repo_gpgcheck: no
  tags:
    - configure

- name: "Darkbulb base packages state is latest"
  become: true
  yum:
    name: "{{ darkbulb_package }}"
    state: latest
    update_cache: yes
  with_items:
    - epel-release
    - kernel-devel
    - python-ncclient
    - git
    - ruby
    - rubygems
    - wget
    - net-tools
    - htop
    - ansible
    - dkms
    - "@Development Tools"
  loop_control:
    loop_var: darkbulb_package
    label: "{{ darkbulb_package }}"
  tags:
    - install
