---
- name: "Ansible Repo is present"
  become: true
  yum_repository:
    name: ansible_release
    description: "CentOS-$releasever / $basearch - Ansible"
    baseurl: "http://releases.ansible.com/ansible/rpm/release/epel-$releasever-$basearch"
    gpgcheck: no
    enabled: yes
    repo_gpgcheck: no
  tags:
    - configure

- name: "Darkbulb base packages state is latest"
  become: true
  yum:
    name: "{{ darkbulb_package }}"
    state: latest
    update_cache: yes
  with_items:
    - epel-release
    - kernel-devel
    - python-ncclient
    - git
    - ruby
    - rubygems
    - wget
    - net-tools
    - htop
    - ansible
    - dkms
    - telnet
    - socat
    - "@Development Tools"
  loop_control:
    loop_var: darkbulb_package
    label: "{{ darkbulb_package }}"
  tags:
    - install

- name: "Group hosts by owner"
  become: false
  group_by:
    key: "{{ owner }}"

- name: "Group hosts by role"
  become: false
  group_by:
    key: "{{ role }}"

- name: "Add entries to /etc/hosts"
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[owner_node].ansible_default_ipv4.address }} {{ owner_node }}"
    line: '{{ hostvars[owner_node].ansible_default_ipv4.address }} {{ owner_node }}'
  with_items:
    - "{{ groups[owner] }}"
  loop_control:
    loop_var: owner_node
