- name: "Ensure owner's account exists"
  become: true
  user:
    name: "{{ owner }}"
    createhome: yes
    home: "/home/{{ owner }}"
    append: yes
  tags:
    - configure

- name: "Create .ssh folder in homedir of owner's account"
  become: true
  become_user: "{{ owner }}"
  file:
    path: "/home/{{ owner }}/.ssh"
    state: directory
    mode: 0755
  tags:
    - config

- name: "Git clone content to home directory of machine owner"
  become: true
  become_user: "{{ owner }}"
  git:
    repo: 'https://github.com/victorock/darkbulb.git'
    version: master
    clone: yes
    dest: "/home/{{ owner }}/darkbulb"
    force: no
  tags:
    - install

- name: "Create image folders in home directory of machine owner"
  become: true
  become_user: "{{ owner }}"
  file:
    path: "/home/{{ owner }}/images/{{ image_dir.path }}"
    state: directory
  with_filetree: "files/images"
  when: image_dir.state == 'directory'
  loop_control:
    loop_var: image_dir
    label: "{{ image_dir.path }}"
  tags:
    - install

- name: "Create local keychain folder structure for {{ owner|quote }}"
  delegate_to: localhost
  become: false
  file:
    path: "files/keychain/{{ owner|quote }}/ssh/"
    state: directory
    mode: 0755
  tags:
    - config

- name: "Create machine owner ssh keys"
  delegate_to: localhost
  become: false
  command: ssh-keygen -b 2048 -t rsa -f files/keychain/{{ owner|quote }}/ssh/id_rsa -N '' -C ''
  args:
    creates: "files/keychain/{{ owner|quote }}/ssh/id_rsa"
  tags:
    - config

- name: "Push owner's id_rsa.pub to authorized_keys"
  become: true
  become_user: "{{ owner }}"
  copy:
    src: "files/keychain/{{ owner }}/ssh/id_rsa.pub"
    dest: "/home/{{ owner }}/.ssh/authorized_keys"
    force: yes
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: 0644
  tags:
    - configure

- name: "Push owner's id_rsa.pub"
  become: true
  become_user: "{{ owner }}"
  copy:
    src: "files/keychain/{{ owner }}/ssh/id_rsa.pub"
    dest: "/home/{{ owner }}/.ssh/"
    force: yes
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: 0644
  tags:
    - configure

- name: "Push owner's id_rsa"
  become: true
  become_user: "{{ owner }}"
  copy:
    src: "files/keychain/{{ owner }}/ssh/id_rsa"
    dest: "/home/{{ owner }}/.ssh/"
    force: yes
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: 0600
  tags:
    - configure
