---
- name: "Vagrant packages state is latest"
  become: true
  yum:
    name: "{{ vagrant_package }}"
    state: latest
    update_cache: yes
  with_items:
    - https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.rpm
  loop_control:
    loop_var: vagrant_package
    label: "{{ vagrant_package }}"
  tags:
    - install

- name: "List Vagrant Plugins"
  become: true
  become_user: "{{ owner }}"
  shell:
    vagrant plugin list
  register: return_vagrant_plugin_list
  changed_when: false
  tags:
    - plugin
    - plugin_add

- name: "Install Vagrant Plugins"
  become: true
  become_user: "{{ owner }}"
  shell:
    vagrant plugin install {{ vagrant_plugin|quote }}
  when:
    - vagrant_plugin not in return_vagrant_plugin_list.stdout
  with_items:
    - hostmanager
    - vagrant-host-shell
    - vagrant-junos
  loop_control:
    loop_var: vagrant_plugin
  tags:
    - plugin
    - plugin_add

- name: "List Vagrant Boxes"
  become: true
  become_user: "{{ owner }}"
  shell:
    vagrant box list
  register: return_vagrant_box_list
  changed_when: false
  tags:
    - box
    - box_add

- name: "Add Vagrant Boxes"
  become: true
  become_user: "{{ owner }}"
  shell:
    vagrant box add {{ vagrant_box|quote }} --provider virtualbox
  when:
    - vagrant_box not in return_vagrant_box_list.stdout
  with_items:
    - ansible/tower
    - centos/7
    - juniper/vqfx10k-re
    - CumulusCommunity/cumulus-vx
  loop_control:
    loop_var: vagrant_box
  tags:
    - box
    - box_add

- name: "Push Vagrant images to machine owner"
  become: true
  become_user: "{{ owner }}"
  copy:
    src: "files/images/boxes/{{ box_file.path }}"
    dest: "/home/{{ owner }}/images/boxes/{{ box_file.path }}"
    force: no
  with_filetree: "files/images/boxes/"
  when: box_file.state == 'file'
  loop_control:
    loop_var: box_file
    label: "{{ box_file.path }}"
  tags:
    - install
