---
- name: "Virtualbox Repo is present"
  become: true
  yum_repository:
    name: virtualbox
    description: "RHEL-7 / CentOS-7 / $basearch - VirtualBox"
#    baseurl: "http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch"
    baseurl: "http://download.virtualbox.org/virtualbox/rpm/el/7/$basearch"
    gpgcheck: no
    enabled: yes
    repo_gpgcheck: yes
    gpgkey: "https://www.virtualbox.org/download/oracle_vbox.asc"
  tags:
    - configure

- name: "Darkbulb Virtualbox packages state is latest"
  become: true
  yum:
    name: "{{ virtualbox_package }}"
    state: latest
    update_cache: yes
  with_items:
    - VirtualBox-5.1
  loop_control:
    loop_var: virtualbox_package
    label: "{{ virtualbox_package }}"
  tags:
    - install

- name: "Check if virtualbox runs fine"
  become: true
  command: /usr/bin/VBoxManage --version
  register: vbox_version
  changed_when: false

- name: "Run vboxconfig to rebuild Virtualbox kernel modules"
  become: true
  command: /usr/sbin/vboxconfig
  when: "'vboxconfig' in vbox_version"

- name: "Ensure owner's is member of vboxusers"
  become: true
  user:
    name: "{{ owner }}"
    createhome: yes
    home: "/home/{{ owner }}"
    groups: vboxusers
    append: yes
  tags:
    - configure
