- name: "GCE Lab Environment"
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: "Parse Topology"
      include_role:
        name: topology

  tasks:
    - name: "Create Topology in Google Cloud"
      include_role:
        name: google-cloud
      vars:
        gce_cloud_instance_name: "{{ go_gce.0.name }}-{{ go_gce.1.node }}"
        owner: "{{ go_gce.0.name }}"
        node: "{{ go_gce.1.node }}"
        role: "{{ go_gce.1.role }}"
      with_nested:
        - "{{ students }}"
        - "{{ kv_node_role }}"
      loop_control:
        loop_var: go_gce
        label: "{{ go_gce.0.name }}-{{ go_gce.1.role }}"
