- name: "GCE Lab Environment"
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: "Validate Topology"
      include_role:
        name: darkbulb
        tasks_from: topology

  tasks:
    - name: "Create GCE Topology"
      include_role:
        name: darkbulb
        tasks_from: gce
      vars:
        gce_cloud_instance_name: "{{ gogce.0.name }}-{{ gogce.1 }}"
        student: "{{ gogce.0.name }}"
      with_nested:
        - "{{ students }}"
        - "{{ nodes }}"
      loop_control:
        loop_var: gogce
        label: "{{ gogce.0.name }}-{{ gogce.1 }}"
