---
- name: "Create and apply configuration on Leaf"
  hosts: juniper:&leaf
  connection: local
  gather_facts: no

  tasks:
    - name: "gather_facts: junos"
      junos_facts:
      register: ansible_junos_facts

    - name: "Underlay Baseline"
      include_role:
        name: underlay-baseline

    - name: "Underlay IP"
      include_role:
        name: underlay-ip

    - name: "Underlay Routing"
      include_role:
        name: underlay-routing

    - name: "Underlay BFD"
      include_role:
        name: underlay-bfd

    - name: "Underlay EBGP"
      include_role:
        name: underlay-ebgp

    - name: "Underlay Policy"
      include_role:
        name: underlay-policy

    - name: "Push config"
      junos_config:
        src: "{{ assemble.config.conf }}"
        backup: yes
        update: override
