interfaces:
  loopback:
    ipv4:
      address: 1.1.1.11
      mask: 255.255.255.255
  ethernet:
    e1:
      name: ethernet1/1
      ipv4:
        address: 172.16.0.3
        mask: 255.255.255.0
    e2:
      name: ethernet1/1
      ipv4:
        address: {{ l3_p2p.link1.2 }}
        mask: 255.255.255.252

  vlan:
    30:
      ipv4:
        address: 172.16.30.3
        mask: 255.255.255.0
