---
- name: "Student Environment"
  hosts: darkbulb
  become: yes
  become_method: sudo

  pre_tasks:
    - name: "Load Configuration"
      include_vars:
        file: vars/main.yml

  tasks:
    - name: "Setup Student Environment"
      include_role:
        name: darkbulb
        tasks_from: setup
