- name: "GCE Lab Environment"
  hosts: localhost
  become: false
  gather_facts: false

  pre_tasks:
    - name: "Load Configuration"
      include_vars:
        file: vars/main.yml

  tasks:

    - name: "Create GCE Environment"
      include_role:
        name: darkbulb
        tasks_from: gce
      vars:
        gce_cloud_instance_base_name: "student"
        gce_cloud_num_instances: "{{ students }}"
